apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: mgnifybranchwater-hl-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
#        image: mgsdev/mgnify-bw-app@sha256:daa0742155de8c296380ef7a20776b511e1a2127a6bb2c9eb95484b8134292de
#        image: mgsdev/mgnify-bw-app@sha256:4fc39e514df763aac59df2bfa8a5a0e50b7d906331c112ea8b21e71f6cdcd560
#        image: mgsdev/mgnify-bw-app:latest
#        image: mgsdev/mgnify-bw-app-alpha@sha256:daa0742155de8c296380ef7a20776b511e1a2127a6bb2c9eb95484b8134292de
#        image: mgsdev/mgnify-bw-app-alpha@sha256:2757f0f421e8ecee7364781c24b8cc6be18049ed165cdcc1dac70f67e9986578
#        image: mgsdev/mgnify-bw-app-alpha@sha256:97086eb4773e10d5ad05ef11001502ab51cb44480c0cff516d5296bb93d1595b
#        image: quay.io/microbiome-informatics/branchwater-app:latest@sha256:df6e6abb7a3822da0681357d1e677010171af7ac818663207f677bd3f09a427e
#        image: quay.io/microbiome-informatics/branchwater-app:latest@sha256:cc4d9bbab7848f45ed8db079f24d7bafa2a58e64ee7be3fde15e281d3b2bbd0a
        image: quay.io/microbiome-informatics/branchwater-app:latest@sha256:ecb5410b12c7f769d5e15b98e2e34faeca4297187b4f14f0128c0f0608160322
#        image: quay.io/microbiome-informatics/branchwater-app:latest@sha256:775f72f5b97ed75da74001292fe7726fd5219110267b7a0291cec243c511b9f4
#        image: quay.io/microbiome-informatics/ebi-metagenomics-client@sha256:3b1b14a67c5d72adc464b36427963ec6e7ebe95ed477f7ca0822b4ecfd361d72
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: prod-env
        volumeMounts:
        - name: signatures-volume
          mountPath: /signatures

        - name: index-updated-sketches-volume
          mountPath: /data

      volumes:
      - name: signatures-volume
        persistentVolumeClaim:
          claimName: signatures-pvc

      - name: index-updated-sketches-volume
        persistentVolumeClaim:
          claimName: index-updated-sketches-pvc
#
#      - name: app-data-volume
#        persistentVolumeClaim:
#          claimName: app-data-pvc
