apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: mgnifybranchwater-hl-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: mgsdev/mgnify-bw-app:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: prod-env
#        volumeMounts:
#        - name: app-volume
#          mountPath: /app

#        - name: app-data-volume
#          mountPath: /data

#      volumes:
#      - name: app-volume
#        persistentVolumeClaim:
#          claimName: app-pvc
#
#      - name: app-data-volume
#        persistentVolumeClaim:
#          claimName: app-data-pvc
