apiVersion: v1
kind: PersistentVolume
metadata:
  name: complete-index-pv
  namespace: mgnifybranchwater-hl-prod
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=3
  nfs:
    server: hh-isi-srv-vlan1496.ebi.ac.uk
    path: /ifs/public/services/metagenomics/branchwater/all_disks_indexed_mount_dir
  #  hostPath:
  #    path: /data
  storageClassName: standard
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: complete-index-pvc
  namespace: mgnifybranchwater-hl-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: complete-index-pv
  storageClassName: standard