apiVersion: v1
kind: PersistentVolume
metadata:
  name: index-pv
  namespace: mgnifybranchwater-hl-prod
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=3
  nfs:
    server: hh-isi-srv-vlan1496.ebi.ac.uk
    path: /ifs/public/services/metagenomics/branchwater/rocksdb_actual/bw_db
#  hostPath:
#    path: /data
  storageClassName: standard
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: index-pvc
  namespace: mgnifybranchwater-hl-prod
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: index-pv
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
  namespace: mgnifybranchwater-hl-prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: app-pv
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: /mnt/branchwater/app
#  storageClassName: standard
#
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: app-pvc
#spec:
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#  volumeName: app-pv
#  storageClassName: standard
