apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebi-metagenomics-client
  namespace: mgnifybranchwater-hl-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ebi-metagenomics-client
  template:
    metadata:
      labels:
        app: ebi-metagenomics-client
    spec:
      containers:
        - name: ebi-metagenomics-client
          image: quay.io/microbiome-informatics/ebi-metagenomics-client@sha256:e9f5f8f18d356c1bd8e4202a2c1e066b9a7820e4d3462049c037d04376dd65d7
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80