apiVersion: v1
kind: PersistentVolume
metadata:
  name: signatures-pv
  namespace: mgnifybranchwater-hl-prod
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=3
#  hostPath:
#    path: /temp_dir

  nfs:
    server: hh-isi-srv-vlan1496.ebi.ac.uk
    path: /ifs/public/rw/metagenomics/sourmash_search/workdir/PRODUCTION/celery/signatures

  storageClassName: standard


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: signatures-pvc
  namespace: mgnifybranchwater-hl-prod
spec:
    accessModes:
    - ReadWriteMany
    resources:
        requests:
          storage: 1Gi
    volumeName: signatures-pv
    storageClassName: standard